admin:
  user:
   per_page: 5
  subject:
    per_page: 10
  suggested_question:
    per_page: 5
  subject_question:
    per_page: 10

bollean:
  true: true
  false: false

exam:
  per_page: 5
  start: "start"
  testing: "testing"
  unchecked: "unchecked"
  checked: "checked"
  status:
    checked: "checked"
  states:
    finish: "Finish"

labels:
  primary: "primary"
  warning: "warning"
  info: "info"
  success: "success"
  danger: "danger"

questions:
  single_choice: "single_choice"
  multiple_choice: "multiple_choice"
  text: "text"
  approved: "approved"

suggested_question:
  status:
    :approved: "Approved"
    :rejected: "Rejected"
